export const imagesPI = [
  {
    image:
      "https://github.com/joaquinbian/joaquinbian/raw/main/screenshotsProjects/LandingPagePhoto.png",
  },
  {
    image:
      "https://github.com/joaquinbian/joaquinbian/raw/main/screenshotsProjects/Photo2.png",
  },
  {
    image:
      "https://github.com/joaquinbian/joaquinbian/raw/main/screenshotsProjects/Photo3.png",
  },
  {
    image:
      "https://github.com/joaquinbian/joaquinbian/raw/main/screenshotsProjects/Photo4.png",
  },
  {
    image:
      "https://github.com/joaquinbian/joaquinbian/raw/main/screenshotsProjects/Photo5.png",
  },
  {
    image:
      "https://github.com/joaquinbian/joaquinbian/raw/main/screenshotsProjects/Photo6.png",
  },
];

export const imagesWeatherApp = [
  {
    image:
      "https://github.com/joaquinbian/joaquinbian/raw/main/screenshotsProjects/WheatherApp1.png",
  },
  {
    image:
      "https://github.com/joaquinbian/joaquinbian/raw/main/screenshotsProjects/WheatherApp2.png",
  },
  {
    image:
      "https://github.com/joaquinbian/joaquinbian/raw/main/screenshotsProjects/WheatherApp3.png",
  },
];
